# fly.toml app configuration file generated for options-day-trading-assistant on 2026-02-01T01:58:00-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "options-day-trading-assistant"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  # Set non-secret environment variables here
  # Persist token and configurables
  TDA_TOKEN_PATH = "/data/token.json"
  LOG_PATH = "/data/logs"
  OUTPUT_DIR = "/data/outputs"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[processes]
  app = "./start.sh"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  cpus = 1
  cpu_kind = "shared"

[mounts]
  source = "options_data"
  destination = "/data"
